/** @type {import('tailwindcss').Config} */

// Map the remaining widths up to double the normal values.
const width: { [key: string]: string } = {};

for (let i = 100; i <= 192; i += 4) {
  width[`${i}`] = `${i / 4}rem`;
}

module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      exotwo: "Exo 2",
      inter: "Inter, sans-serif",
      jetbrains: "JetBrains Mono, monospace",
      kaushan: "Kaushan Script, cursive",
      manrope: "Manrope, sans-serif",
      marienda: "Marienda, cursive",
      montserrat: "Montserrat, sans-serif",
      quint: "Quintessential, cursive",
      satisfy: "Satisfy, cursive",
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        black: "#000",
        white: "#fff",
        primary: "#b803a6",
        "primary-hover": "#7E0272",
        "brand-100": "#f4f6fc",
        "brand-200": "#E1E6F4",
        "brand-300": "#d3daef",
        "brand-400": "#C0CAE8",
        "brand-500": "#9BA9D4",
        "brand-600": "#7182B4",
        "brand-700": "#475889",
        "brand-800": "#273459",
        "brand-900": "#1A1A32",
        "brand-950": "#0E0E24",
        "brand-dark": "#0e0e24",
        "brand-dark-hover": "#1a1a32",
        "brand-lighter": "#f4f6fc",
        "brand-light": "#d3daef",
        "dark-turquoise": "#0097b2",
      },
      dropShadow: {
        "white-xl": "0 0 0.5rem rgba(100, 255, 100, 0.4)",
      },
      height: {
        "one-fifty": "150vh",
      },
      keyframes: {
        underline: {
          "0%": { "border-width": "0" },
          "100%": { "border-width": "100%" },
        },
        animation: {
          underline: "underline 2s ease-in-out infinite",
        },
      },
      // This line is generated by the loop at the top of the page.
      width,
    },
  },
  plugins: [],
};
