// React/Next imports
import type { Metadata } from "next";

// Component imports
import Layout from "@/components/structure/Layout";

// Other imports
import "./globals.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`mx-auto font-montserrat text-brand-dark`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
